

name: Node.js CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
   
    - name: Login to Docker Hub and push the build
      run: |
        docker login --username "${{ secrets.Docker_username }}" --password "${{ secrets.Docker_password }}"
        docker build . --file Dockerfile -t ismayil10/ethexplorer-react
        docker push ismayil10/ethexplorer-react

    - name: Configure SSH
      run: |
          git config --global user.email "mohammedismayil10@gmail.com"
          git config --global user.name "mohammedismayil"
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName "${{ secrets.SSH_HOST }}"
            User "${{ secrets.SSH_USER }}"
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
    - name: Run the app using docker
      run: |
         ssh staging 'sudo docker pull ismayil10/ethexplorer-react'
         ssh staging 'sudo docker stop explorer'
         ssh staging 'sudo docker run --name explorer -it -d -p 3000:3000 ismayil10/ethexplorer-react'